language: node_js

node_js:
  - 'iojs'

sudo: false

addons:
  apt:
    packages:
      - libzmq3-dev
      - pkg-config

env:
  matrix:
    #- PLATFORM=darwin
    #- PLATFORM=win32
    - PLATFORM=linux

before_install:
  - npm install -g node-gyp

install:
  - npm install
